// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                int64              `json:"id"`
	Username          string             `json:"username"`
	FullName          string             `json:"full_name"`
	Sex               string             `json:"sex"`
	Age               int32              `json:"age"`
	Email             string             `json:"email"`
	Phone             string             `json:"phone"`
	HashedPassword    string             `json:"hashed_password"`
	Avatar            string             `json:"avatar"`
	Status            string             `json:"status"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
